name: Target Multiple Node.js Versions 12 and Operating Systems ubuntu 
on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: $
    strategy:
      matrix:
        os: ubuntu-latest
        node: 12
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: $
      - uses: actions/checkout@v1
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome src/tests"